name: test_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - aiohttp
  - tornado
  - sqlalchemy
  - intake
  - requests
  - msgpack-numpy
  - pytest
  - fsspec
  - pip
  - pytest
